# Generated by Django 3.2.3 on 2024-02-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240220_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-id'], 'verbose_name': 'Подписка на пользователя', 'verbose_name_plural': 'Подписки на пользователя'},
        ),
    ]
